name: 'dream-cast-net'
dataset:
  combine_data: false
  num_channels: 14
  img_height: 40
  img_width: 160
  seq_len: 6
  lead_time: 12
  layout: "NTHWC"
  normalize: masked_min-max
  include_labels: false
  save_test: false
  num_train_chunks: 10

optim:
  batch_size: 16
  float32_matmul_precision: "high"
  seed: 0
  method: "adam"
  lr: 0.0001
  max_epochs: 150
  num_workers: 8
  # # scheduler
  # warmup_percentage: 0.1
  # lr_scheduler_mode: "cosine"
  # min_lr_ratio: 1.0e-3
  # warmup_min_lr_ratio: 0.1

model:
  down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
  in_channels: 14
  block_out_channels: [128, 256, 512, 512]  # downsample `len(block_out_channels) - 1` times
  act_fn: 'silu'
  latent_channels: 64
  up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
  norm_num_groups: 32
  layers_per_block: 2
  out_channels: 14
  loss:
    disc_start: 8001
    kl_weight: 1e-6
    disc_weight: 0.5
    perceptual_weight: 0.0  # ncep does not have RGB channels
    disc_in_channels: 14
